name:                    S3/CloudFront CI/CD

on:
  push:
    branches:            [main]
  pull_request:
    branches:            [main]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on:             ubuntu-latest
    environment:        
      name: s3-cloudfront
      url:  https://engjole.net
    steps:
      - uses:            actions/checkout@v2
        with:
          submodules:  true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name:            Setup Hugo
        uses:            peaceiris/actions-hugo@v2
        with:
          hugo-version:  "latest"
          extended:  true

      - name:            Build static content
        run:             hugo --minify

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::377420491642:role/s3-cloudfront-deploy
          role-session-name: s3deploy
          aws-region: us-west-2

      - name:            Deploy to S3 and CloudFront
        run: |
          S3_BUCKET=${{ secrets.S3_BUCKET }}
          CLOUDFRONT_ID=${{ secrets.CLOUDFRONT_ID }}
          sed -i "s|S3_BUCKET|${S3_BUCKET}|g" config.toml
          sed -i "s|CLOUDFRONT_ID|${CLOUDFRONT_ID}|g" config.toml
          hugo deploy
